#:schema https://www.schemastore.org/cargo.json

[workspace]
resolver = "3"
members = ["apps/*", "apps/metaball/apps/*"]

[workspace.package]
edition = "2024"
license = "MIT"

[workspace.dependencies]
nannou = { git = "https://github.com/umitsukidev/nannou.git", rev = "b62a4060b95958982d2f2795c12051febd8c6f17" }
rayon = "1.12.0"
bytemuck = { version = "1.25.0", features = ["derive"] }
opencv = "0.99.0"
ndarray = "0.17.2"
derive_more = "2.1.1"

[workspace.lints.clippy]
all = "warn"

[profile.wasm-release]
inherits = "release"
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
