#:schema https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json

language = "en,ja"
ignorePaths = ["Cargo.lock", "target"]
dictionaries = ["summer-term-rust"]

[[dictionaryDefinitions]]
name = "summer-term-rust"
path = "./cspell.txt"
addWords = true
